import { api } from './request'

export const getDashboard = () => api.get('/community/dashboard')
export const getElders = (params) => api.get('/community/elders', params)
export const createElder = (data) => api.post('/community/elders', data)
export const updateElder = (id, data) => api.put(`/community/elders/${id}`, data)
export const getElder = (id) => api.get(`/community/elders/${id}`)
export const getElderFull = (id) => api.get(`/community/elders/${id}/full`)
export const getElderTimeline = (id, params) => api.get(`/community/elders/${id}/timeline`, params)
export const getElderActivitySummary = (id, params) => api.get(`/community/elders/${id}/activity-summary`, params)
export const recalculateRisk = (id) => api.post(`/community/elders/${id}/risk/recalculate`)
export const getAiAnalysis = (id) => api.get(`/community/elders/${id}/risk/ai-analysis`)
export const getAlertRules = () => api.get('/community/alert-rules')
export const seedAlertRules = () => api.post('/community/alert-rules/seed')
export const updateAlertRule = (id, data) => api.put(`/community/alert-rules/${id}`, data)
export const getPendingAlerts = () => api.get('/community/alerts/pending')
export const respondAlert = (id, data) => api.post(`/community/alerts/${id}/respond`, data)
export const getRiskRanking = () => api.get('/community/risk-ranking')
export const getBuildingElders = (building) => api.get('/community/dashboard/building', { building })
export const confirmElderActive = (id) => api.post(`/community/elders/${id}/confirm-active`)
export const getElderDayActivity = (id, date) => api.get(`/community/elders/${id}/day-activity`, { date })
