"""add volunteer tables

Revision ID: 25d6f26496f2
Revises: 98036f2c0f40
Create Date: 2026-06-30 14:43:56.805360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d6f26496f2'
down_revision: Union[str, None] = '98036f2c0f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('elder_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('available_points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['elder_id'], ['community_elders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('help_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('community_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.String(length=16), nullable=False),
    sa.Column('target_elder_id', sa.Uuid(), nullable=True),
    sa.Column('point_value', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['community_workers.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['target_elder_id'], ['community_elders.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['community_workers.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('point_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('volunteer_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=16), nullable=True),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('point_transactions')
    op.drop_table('help_tasks')
    op.drop_table('volunteer_profiles')
    # ### end Alembic commands ###
