"""add resolution_note to community_events

Revision ID: 98036f2c0f40
Revises: b1c2a761b8ec
Create Date: 2026-06-30 14:39:12.029562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98036f2c0f40'
down_revision: Union[str, None] = 'b1c2a761b8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_events', sa.Column('resolution_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_events', 'resolution_note')
    # ### end Alembic commands ###
