"""add risk_score_snapshots table

Revision ID: b1c2a761b8ec
Revises: 4de149b8127f
Create Date: 2026-06-25 17:59:21.640168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1c2a761b8ec'
down_revision: Union[str, None] = '4de149b8127f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_score_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('elder_id', sa.UUID(), nullable=False),
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['elder_id'], ['community_elders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('elder_id', 'snapshot_date', name='uq_risk_snapshot_elder_date')
    )
    op.alter_column('canteen_records', 'community_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('canteen_records', 'source_format',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'text'::character varying"))
    op.alter_column('canteen_records', 'parse_status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('canteen_records', 'recorded_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('canteen_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('communities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('community_elders', 'community_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('community_elders', 'elder_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('community_elders', 'care_level',
               existing_type=sa.VARCHAR(length=1),
               nullable=False,
               existing_server_default=sa.text("'C'::character varying"))
    op.alter_column('community_elders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('community_elders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('community_events', 'community_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('community_events', 'elder_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('community_events', 'severity',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'info'::character varying"))
    op.alter_column('community_events', 'is_resolved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('community_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('community_worker_assignments', 'worker_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('community_worker_assignments', 'community_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('community_worker_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('community_workers', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('community_workers', 'community_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('community_workers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('community_workers_phone_key', 'community_workers', type_='unique')
    op.create_index(op.f('ix_community_workers_phone'), 'community_workers', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_workers_phone'), table_name='community_workers')
    op.create_unique_constraint('community_workers_phone_key', 'community_workers', ['phone'])
    op.alter_column('community_workers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('community_workers', 'community_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('community_workers', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('community_worker_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('community_worker_assignments', 'community_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('community_worker_assignments', 'worker_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('community_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('community_events', 'is_resolved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('community_events', 'severity',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'info'::character varying"))
    op.alter_column('community_events', 'elder_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('community_events', 'community_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('community_elders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('community_elders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('community_elders', 'care_level',
               existing_type=sa.VARCHAR(length=1),
               nullable=True,
               existing_server_default=sa.text("'C'::character varying"))
    op.alter_column('community_elders', 'elder_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('community_elders', 'community_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('communities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('canteen_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('canteen_records', 'recorded_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('canteen_records', 'parse_status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('canteen_records', 'source_format',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'text'::character varying"))
    op.alter_column('canteen_records', 'community_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('risk_score_snapshots')
    # ### end Alembic commands ###
